# Generated by Django 4.2.7 on 2023-12-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, verbose_name="Nom de la categorie"),
                ),
                ("image", models.ImageField(upload_to="Categories")),
            ],
        ),
    ]
